import sqlite3
from sqlite3 import Error
from database import DB_open, DB_saveADSBInfo
from peewee.peewee import Model, CharField, DecimalField, BigIntegerField, SqliteDatabase


class ADSBInfo(Model):
    collector = CharField(max_length=64, null=True, default="")

    modeSCode = CharField(max_length=16, null=True, default="")
    callsign = CharField(max_length=16, null=True, default="")

    # Airplane position
    latitude = DecimalField(max_digits=40, decimal_places=20, default=0.0)
    longitude = DecimalField(max_digits=40, decimal_places=20, default=0.0)
    altitude = DecimalField(max_digits=40, decimal_places=20, default=0.0)

    # Airplane velocity
    verticalVelocity = DecimalField(max_digits=40, decimal_places=20, default=0.0)
    horizontalVelocity = DecimalField(max_digits=40, decimal_places=20, default=0.0)

    # Airplane angle
    groundTrackHeading = DecimalField(max_digits=40, decimal_places=20, default=0.0)

    # Observation date time generated by server
    timestamp = BigIntegerField(default=0)
    timestampSent = BigIntegerField(default=0)

    # Originals ADS-B messages
    messageDataId = CharField(max_length=100, default='')
    messageDataPositionEven = CharField(max_length=100, default='')
    messageDataPositionOdd = CharField(max_length=100, default='')
    messageDataVelocity = CharField(max_length=100, default='')



def main():
    database = r"radarlivre_v4.db"

    con = DB_open(database)
    adsb = ADSBInfo()

    adsb.collector = "12345687890"
    adsb.modeSCode = "E1E2E3"
    adsb.callsign = "GOL123"
    adsb.latitude = -4.764374
    adsb.longitude = -39.116211
    adsb.altitude = 22300
    adsb.verticalVelocity = -2880
    adsb.horizontalVelocity = 460.508423
    adsb.groundTrackHeading = 354.017029
    adsb.timestamp = 123456789
    adsb.timestampSent = 123456789
    adsb.messageDataId = "8DE491A120501373E39C603B0D55"
    adsb.messageDataPositionEven = "8DE491A1587570D2112DC1359251"
    adsb.messageDataPositionOdd = "8DE491A1587544E06F65595BF018"
    adsb.messageDataVelocity = "8DE491A19914313968B837E83E8D"

    adsb.insert()
    
    with con:
            value = ("12345687890","E1E2E3","GOL123", -4.764374, -39.116211,
            22300,-2880,460.508423, 354.017029,123456789,123456789,
            "8DE491A120501373E39C603B0D55","8DE491A1587570D2112DC1359251",
            "8DE491A1587544E06F65595BF018", "8DE491A19914313968B837E83E8D")

            DB_saveADSBInfo(con, adsb)

    con.close()

if __name__ == '__main__':
    main()